[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  publish = "dist/spa"
  command = "quasar build"

[context.production.environment]
  APP_NAME = "Telos Web Wallet"
  NODE_VERSION = "14"
  NETWORK="mainnet"

[context.develop.environment]
  APP_NAME = "Telos Web Wallet"
  NODE_VERSION = "14"
  NETWORK="testnet"
